on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bnkacr.azurecr.io
        username: ${{ secrets.acr_bnkacr_username }}
        password: ${{ secrets.acr_bnkacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      working-directory: ./myAPI
      run: |
        docker build "$GITHUB_WORKSPACE/myAPI" -f  "myAPI/Dockerfile" -t bnkacr.azurecr.io/bnkncussharedaks01:${{ github.sha }} --label dockerfile-path=myAPI/Dockerfile
        docker push bnkacr.azurecr.io/bnkncussharedaks01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bnkncussharedaks01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mmc22-poc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mmc22-poc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mmc22-poc
        container-registry-url: bnkacr.azurecr.io
        container-registry-username: ${{ secrets.acr_bnkacr_username }}
        container-registry-password: ${{ secrets.acr_bnkacr_password }}
        secret-name: bnkncussharedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mmc22-poc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          bnkacr.azurecr.io/bnkncussharedaks01:${{ github.sha }}
        imagepullsecrets: |
          bnkncussharedockerauth
